apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxservice
  name: nginxservice
spec:
  type: NodePort
  ports:
    # The port that this service should serve on.
  - port: 80
    nodePort: 30096
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: nginx
